name: Hitting the cronjob endpoint every hour to update Google Sheet Content

on:
  schedule:
    - cron: '15 * * * *'
jobs:
  build:
    name: Send a GET request via wget
    runs-on: ubuntu-latest
    steps:
      - name: wget request
        run: wget https://api.project-ias.com/cron_gsheet